import * as os from "os";
import { Monitor } from "./monitor";
import { HtmlPage, htmlTemplate } from "./common";

export class Home implements HtmlPage {
  readonly PATH: string = "/";

  private monitor: Monitor;

  constructor(monitor: Monitor) {
    this.monitor = monitor;
    console.log("Homepage factory ready.");
  }

  buildHtml(): string {
    const visitorName = "Visitor";
    const serverTime = new Date().toLocaleTimeString();

    // Use a template literal to build the HTML dynamically
    // Uses https://jdan.github.io/98.css/.
    return htmlTemplate(`
      <div class="window" style="margin: 32px; width: 250px">
        <div class="title-bar">
          <div class="title-bar-text">
            beekley.xyz
          </div>

          <div class="title-bar-controls">
            <button aria-label="Close"></button>
          </div>
        </div>
        <div class="window-body">
          <p>Hello, ${visitorName}!</p>
          <p>This page was generated by a Node ${
            process.versions.node
          } server on ${os.hostname()} (${os.machine()}).</p>
          <p>Server time is: <strong>${serverTime}</strong></p>
          <p>Mon data: ${this.monitor.data.length}</p>
          ${this.monitor.renderSvg()}
          <section class="field-row" style="justify-content: flex-end">
            <button>OK</button>
            <button>Cancel</button>
          </section>
        </div>
      </div>
    `);
  }
}
