// Import only the built-in http module
import * as http from "http";

const PORT = 3000;

/**
 * Dynamically builds an HTML response.
 * @returns A complete HTML string.
 */
function buildHtml(): string {
  const visitorName = "Visitor";
  const serverTime = new Date().toLocaleTimeString();

  // Use a template literal to build the HTML dynamically
  // Uses https://jdan.github.io/98.css/.
  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Dynamic Node.js Server</title>
      <link
        rel="stylesheet"
        href="https://unpkg.com/98.css"
      >
    </head>
    <body>
      <main>
        <div class="window" style="margin: 32px; width: 250px">
          <div class="title-bar">
            <div class="title-bar-text">
              beekley.xyz
            </div>

            <div class="title-bar-controls">
              <button aria-label="Close"></button>
            </div>
          </div>
          <div class="window-body">
            <p>Hello, ${visitorName}!</p>
            <p>This page was generated by a Node ${process.versions.node} server.</p>
            <p>Server time is: <strong>${serverTime}</strong></p>
            <section class="field-row" style="justify-content: flex-end">
              <button>OK</button>
              <button>Cancel</button>
            </section>
          </div>
        </div>
      </main>
    </body>
    </html>
  `;
}

// Create the server
const server = http.createServer(
  (req: http.IncomingMessage, res: http.ServerResponse) => {
    try {
      // We need a full URL to parse query parameters
      const url = new URL(req.url || "/", `http://${req.headers.host}`);

      // Basic routing
      if (url.pathname === "/") {
        // Build the dynamic HTML
        const htmlResponse = buildHtml();

        // Send the response
        res.writeHead(200, { "Content-Type": "text/html" });
        res.end(htmlResponse);
      } else {
        // Handle 404 Not Found
        res.writeHead(404, { "Content-Type": "text/plain" });
        res.end("404 Not Found");
      }
    } catch (error) {
      console.error("Error handling request:", error);
      res.writeHead(500, { "Content-Type": "text/plain" });
      res.end("Internal Server Error");
    }
  }
);

// Start listening for requests
server.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}/`);
});
